### ISSUE TITLE
Configure local k8s environment to run db upgrade tasks in init-container

### ISSUE THREAD

**Issue by spbolton** [dotCMS/helm-charts#17]
Replicate behavior used in "Configurator" Quarkus application deployment here https://github.com/dotCMS/internal-infrastructure/blob/c9570d7c272b85da27f6e31044d47284824a8253/dot-analytics/deployment/charts/configurator/templates/deployment.yaml 

Make use of the k8s-wait-for image to have the init container wait for successful completion of the job.
```
initContainers:
        - args:
            - job
            - {{ .Release.Name }}-init-job-{{ .Release.Revision }}
          image: groundnuty/k8s-wait-for:no-root-v1.7
          imagePullPolicy: IfNotPresent
          name: init
```

I the above case the job name defined here and matched in the job.yaml file will re-run if the .Release.Revison changes.   We should confirm that this is the expected behavior.

 and the associated job here https://github.com/dotCMS/internal-infrastructure/blob/d72b323af10b025967131bf55f132aa90ce5870c/dot-analytics/deployment/charts/configurator/templates/job.yaml

To cause changes to depolyments of the dotcms stateful set to run the DotCMS server configured just like in the main stateful set but with the DOT_SHUTDOWN_ON_STARTUP flag set to true.   The DotCMS image used must have this flag enabled with the previous task.  

If this is enabled we can add the flag to the main stateful set to not try to re-run the startup tasks.  

Make sure to test that the init container successfully runs the upgrade tasks and completes allowing the replicas to start up.   Test and assess behavior when An upgrade task fails.   The init container should retry (Question what do we do if retry is never going to work e.g. the database is messed up, or the upgrade tasks sql will always error without a fix )  Do we retry forever?)
