### ISSUE TITLE
Scale down/up in Helm Hooks

### ISSUE THREAD

**Issue by spbolton** [dotCMS/helm-charts#28]
# Implement Scale Down/Up Helm Hooks

Add Helm hooks to handle scaling the dotCMS deployment down before upgrades and back up after, but only when specifically enabled via configuration.

## What needs to be done
- [ ] Create pre-upgrade hook
  - [ ] Check `.Values.dotcms.scaleDownBeforeUpgrade` flag
  - [ ] If true, scale dotCMS deployment to 0
  - [ ] Store current replica count from `.Values.dotcms.replicas`
  - [ ] Skip if flag is false

- [ ] Create post-upgrade hook
  - [ ] Check if we scaled down (pre-upgrade hook ran)
  - [ ] Scale back up to original replica count from `.Values.dotcms.replicas`
  - [ ] Ensure proper ordering with other post-upgrade activities

- [ ] Add helm value configurations
  - [ ] Add `scaleDownBeforeUpgrade` boolean flag (default: false)
  - [ ] Document in values.yaml
  - [ ] Add example in values documentation

## Implementation details
- Use Kubernetes jobs for the hooks
- Pre-upgrade hook should use `helm.sh/hook: pre-upgrade`
- Post-upgrade hook should use `helm.sh/hook: post-upgrade`
- Both hooks need proper weight/ordering values
- Jobs should clean up after themselves (ttl)

## Testing needed
- [ ] Verify scaling works when flag is true
- [ ] Verify nothing scales when flag is false
- [ ] Check proper scale up to original replica count
- [ ] Test with concurrent upgrades
- [ ] Verify cleanup of hook jobs

## Example Values
```yaml
dotcms:
  scaleDownBeforeUpgrade: true  # Enable scale down during upgrade
  replicas: 3                   # Will scale to 0 then back to 3
```

Example prototype implementation
```
# templates/hooks/pre-upgrade-scale.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-pre-upgrade-scale
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"  # Run early in pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      name: {{ .Release.Name }}-pre-upgrade-scale
    spec:
      serviceAccountName: {{ .Release.Name }}-hook-sa
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              # Only scale if flag is set
              if [ "{{ .Values.dotcms.scaleDownBeforeUpgrade }}" = "true" ]; then
                echo "Scaling down dotCMS deployment..."
                # Store current replica count in configmap for post-upgrade
                kubectl create configmap {{ .Release.Name }}-scale-data \
                  --from-literal=replicas="{{ .Values.dotcms.replicas }}"
                
                # Scale down the deployment
                kubectl scale deployment {{ .Release.Name }}-dotcms --replicas=0
                
                # Wait for scale down to complete
                kubectl rollout status deployment {{ .Release.Name }}-dotcms
              else
                echo "Scale down not enabled, skipping..."
              fi
      restartPolicy: Never

---
# templates/hooks/post-upgrade-scale.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-post-upgrade-scale
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "5"  # Run after other post-upgrade tasks
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      name: {{ .Release.Name }}-post-upgrade-scale
    spec:
      serviceAccountName: {{ .Release.Name }}-hook-sa
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              # Check if we need to scale back up
              if kubectl get configmap {{ .Release.Name }}-scale-data &> /dev/null; then
                # Get stored replica count
                REPLICAS=$(kubectl get configmap {{ .Release.Name }}-scale-data -o jsonpath='{.data.replicas}')
                
                echo "Scaling dotCMS deployment back to $REPLICAS replicas..."
                kubectl scale deployment {{ .Release.Name }}-dotcms --replicas=$REPLICAS
                
                # Wait for scale up to complete
                kubectl rollout status deployment {{ .Release.Name }}-dotcms
                
                # Clean up configmap
                kubectl delete configmap {{ .Release.Name }}-scale-data
              else
                echo "No scale down was performed, skipping..."
              fi
      restartPolicy: Never

---
# templates/hooks/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-hook-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-hook-role
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["get", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-hook-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-hook-sa
roleRef:
  kind: Role
  name: {{ .Release.Name }}-hook-role
  apiGroup: rbac.authorization.k8s.io

---
# values.yaml snippet
dotcms:
  # Enable scale down during upgrade
  scaleDownBeforeUpgrade: false
  # Number of replicas to run
  replicas: 3
```
